version: "3.4"

services: 
  elasticsearch:
    build:
      context: ./elasticsearch
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "c:\\avs\\elasticsearch\\data:c:/es-data"
      - "c:\\avs\\elasticsearch\\logs:c:/es-logs"
  kibana:
    build:
      context: ./kibana
    image: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
