version: "3.4"

services: 
  elasticsearch:
    environment:
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
  
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:5.6.6
    networks:
      - es-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  es-net :

volumes:
  es-data:
