version: "3.4"

services: 
  elasticsearch:
    environment:
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    networks:
      - esnet
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - c:\\avs\\elasticsearch\\data:/usr/share/elasticsearch/data
  
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    networks:
      - esnet
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  esnet :